### ISSUE TITLE
Protégé don't list OWL classes from 2.8.0 toolkit version

### ISSUE THREAD

**Issue by erfelipe** [IHTSDO/snomed-owl-toolkit#34]
I tried using version 2.8.0 of the RF2 (SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z) to OWL converter, but Protégé 5.5 does not recognize the classes. So I used the 2.7.1 converter and it worked normally.

**Comment by kaicode** [comment]
Hi @erfelipe,

Thanks for letting us know you have experienced a problem. 

I've just uploaded the artifacts for release 2.9.0, I didn't realise they were not up yet. Just now with 2.9.0 I was able to generate an OWL file from SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z.zip which Protégé 5.5 will load. 

The OWL file created by 2.8.0 or 2.9.0 is bigger than that created by 2.7.0 because now all descriptions are included. Fully Specified Names use the rdfs:label annotation and Preferred Terms use the skos:prefLabel. 

If the file loads in Protégé but you can't see the labels, this could be due to your display preferences. To get it working in Protégé under *View* > *Custom rendering...* > Select *"Render by annotation property (e.g., rdfs:label, skos:prefLabel)"*.

If however Protégé fails to load the file it may not have enough memory.

I hope that helps!
Kind regards,
Kai

**Comment by erfelipe** [comment]
Thank you very much for your attention, @kaicode . 
I'll try right now. 

Best regards !

**Comment by erfelipe** [comment]
Hi @kaicode ,
I'm try to use 2.9.0 toolkit version, and I receive this problem (from log):
2020-01-07 21:29:53,973 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - 0 active axioms loaded
org.snomed.otf.owltoolkit.conversion.ConversionException: No Stated Relationships or Axioms were found. An Ontology file can not be produced.
	at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:51)
	at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
	at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
	at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

Can you try the RF2 conversion in your machine? The command line that I'm try to use, is:   java -jar snomed-owl-toolkit-2.9.0-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20190731T120000Z.zip 

Regards,
