### ISSUE TITLE
Unable to run snomed-owl-toolkit-2.10.1-executable.jar

### ISSUE THREAD

**Issue by RafaelDaddio** [IHTSDO/snomed-owl-toolkit#48]
Hello,

I'm trying to run the RDF-to-OWL toolkit from command line but I keep getting a set of Exceptions. Can you provide advise on this?

Details:
Java version: 
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
I am trying to convert the following SNOMED releases. Both of them have Full, Snapshot and Delta folders. Both of them generate the same error.
- SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip
- UK_SNOMEDCT2_30.0.0_20200805000001.zip (UK Clinical extension for the same period)

I set those files in the same folder as the .jar and run the following command line:
`java -Xms4g -jar snomed-owl-toolkit-2.10.1-executable.jar -rf2-to-owl -rf2-snapshot-archives SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip -version 20200731T12`

Then I receive the following errors:
```
Creating Ontology using the following options:
  Snapshot archives: [SnomedCT_InternationalRF2_PRODUCTION_20200731T120000Z.zip]
  Delta archive: -none-
  Ontology URI: http://snomed.info/sct/900000000000207008
  Ontology Version: 20200731T12
  Include Description Annotations: true

2021-04-29 12:20:57,633 [INFO  ] [main] org.snomed.otf.owltoolkit.conversion.RF2ToOWLService - Loading RF2 files
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.ExceptionInInitializerError
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
        at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
        at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
        at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
        at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
        at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97)
        at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
        at org.snomed.otf.owltoolkit.taxonomy.AxiomDeserialiser.<init>(AxiomDeserialiser.java:33)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyLoader.<init>(SnomedTaxonomyLoader.java:54)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyLoader.<init>(SnomedTaxonomyLoader.java:63)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:117)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:81)
        at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:45)
        at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
        at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
        at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
        ... 8 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @39ba5a14
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
        ... 39 more

```
Initially I thought the problem would be due trying to work with the UK Extension, but since the International release also presents problems, I'm lost in what I should do.

Thank you for your time,
Rafael

**Comment by sschaat** [comment]
I have similar error messages when using Windows. 
With Ubuntu it works, I only get some warnings.

**Comment by kaicode** [comment]
Please use java version 11 to avoid this unresolved issue in later versions.
