### ISSUE TITLE
rf2-to-owl fails with July 2021 International Beta

### ISSUE THREAD

**Issue by rwynne** [IHTSDO/snomed-owl-toolkit#53]
Hi,

I'm not sure if this is a converter or data issue, but when I try to transform the Beta July 2021 Release RF2 to OWL with version 3.0.3 the following stacktrace is returned.

Should I try a different command, or possibly a previous version?

Thanks.

```
-bash-4.2$ java -jar snomed-owl-toolkit-3.0.3-executable.jar -rf2-to-owl -rf2-snapshot-archives xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip

Creating Ontology using the following options:
  Snapshot archives: [xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip]
  Delta archive: -none-
  Ontology URI: http://snomed.info/sct/900000000000207008
  Ontology Version: 20210611
  Include Description Annotations: true

2021-06-11 10:42:46,413 [INFO  ] [main] org.snomed.otf.owltoolkit.conversion.RF2ToOWLService - Loading RF2 files
java.lang.IllegalStateException: No Snapshot files found in archive: /tmp/temp-rf2-unzip745347076429886198/1/release.zip
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.unzipRelease(ReleaseImporter.java:140)
        at org.ihtsdo.otf.snomedboot.ReleaseImporter.loadEffectiveSnapshotReleaseFileStreams(ReleaseImporter.java:83)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:121)
        at org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder.build(SnomedTaxonomyBuilder.java:82)
        at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:45)
        at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
        at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
        at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by kaicode** [comment]
Hi there,

Just tested with the beta and it seems okay here. My output starts:
```
$ java -Xms4g -jar target/snomed-owl-toolkit-3.0.3-executable.jar -rf2-snapshot-archives ../../Downloads/xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip 

Creating Ontology using the following options:
  Snapshot archives: [../../Downloads/xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip]
  Delta archive: -none-
  Ontology URI: http://snomed.info/sct/900000000000207008
  Ontology Version: 20210611
  Include Description Annotations: true

2021-06-11 15:53:28,593 [INFO  ] [main] org.snomed.otf.owltoolkit.conversion.RF2ToOWLService - Loading RF2 files
2021-06-11 15:53:40,649 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Unzipping file to /var/folders/q9/rk7j9vwn1t19z0fc06qjyrkh0000gn/T/temp-rf2-unzip6021230568542732731/1/xsct2_Concept_Snapshot_INT_20210731.txt
2021-06-11 15:53:40,946 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Unzipping file to /var/folders/q9/rk7j9vwn1t19z0fc06qjyrkh0000gn/T/temp-rf2-unzip6021230568542732731/1/xsct2_Description_Snapshot-en_INT_20210731.txt
2021-06-11 15:53:42,906 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Unzipping file to /var/folders/q9/rk7j9vwn1t19z0fc06qjyrkh0000gn/T/temp-rf2-unzip6021230568542732731/1/xsct2_StatedRelationship_Snapshot_INT_20210731.txt
2021-06-11 15:53:43,949 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Unzipping file to /var/folders/q9/rk7j9vwn1t19z0fc06qjyrkh0000gn/T/temp-rf2-unzip6021230568542732731/1/xsct2_Relationship_Snapshot_INT_20210731.txt
2021-06-11 15:53:47,023 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Unzipping file to /var/folders/q9/rk7j9vwn1t19z0fc06qjyrkh0000gn/T/temp-rf2-unzip6021230568542732731/1/xsct2_RelationshipConcreteValues_Snapshot_INT_20210731.txt
...
```

I wonder if there is an issue with the zip file you have? It should be about 480Mb.
Also please check the output of this command, to list the Snapshot entries within the zip file:
```
unzip -l xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip | grep Snapshot
```

Mine starts:
```
$ unzip -l ../../Downloads/xSnomedCT_InternationalRF2_BETA_20210731T120000Z.zip | grep Snapshot
        0  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/
        0  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/
 29140809  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/xsct2_Concept_Snapshot_INT_20210731.txt
201470381  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/xsct2_Description_Snapshot-en_INT_20210731.txt
114384928  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/xsct2_StatedRelationship_Snapshot_INT_20210731.txt
349674342  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/xsct2_Relationship_Snapshot_INT_20210731.txt
  3194948  06-03-2021 10:46   xSnomedCT_InternationalRF2_BETA_20210731T120000Z/Snapshot/Terminology/xsct2_RelationshipConcreteValues_Snapshot_INT_20210731.txt
....
```

**Comment by rwynne** [comment]
This was silly.  Our secure email application wrapped the zip distribution in another zip file with the same name before download.  I unzipped the download to the zip distribution and now the program runs just fine.

Thank you, Kai. 😊

**Comment by kaicode** [comment]
That's good news! I'm glad you got it sorted. 
Impressive security system too! 😄
