### ISSUE TITLE
Netherlands Edition Release  : Question

### ISSUE THREAD

**Issue by J-rijn** [IHTSDO/snomed-owl-toolkit#57]
Not sure if this is the right place for my question:

It seems the toolkit doesn't handle the Netherlands Edition release quite well.
I tried for the 3 most recent Snomed CT releases (Sept 30 2021, Mar 31 2021 and Sept 30 2020)
Not quite sure what goes wrong, performance is inconsistent as well: sometimes an .owl file gets created containing just a few random entities, sometimes it says an owll file cannot be produced.

`$ java -jar snomed-owl-toolkit-3.0.3-executable.jar -rf2-to-owl -rf2-snapshot-ar                                                                              chives SnomedCT_Netherlands_EditionRelease_PRODUCTION_20200930T120000Z.zip

Creating Ontology using the following options:
  Snapshot archives: [SnomedCT_Netherlands_EditionRelease_PRODUCTION_20200930T12                                                                              0000Z.zip]
  Delta archive: -none-
  Ontology URI: http://snomed.info/sct/900000000000207008
  Ontology Version: 20211021
  Include Description Annotations: true

2021-10-21 16:57:31,481 [INFO  ] [main] org.snomed.otf.owltoolkit.conversion.RF2                                                                              ToOWLService - Loading RF2 files
2021-10-21 16:57:44,220 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cRefset_AssociationSnapshot_NL_20200930.txt
2021-10-21 16:57:44,402 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cRefset_AttributeValueSnapshot_NL_20200930.txt
2021-10-21 16:57:44,938 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_Refset_SimpleSnapshot_NL_20200930.txt
2021-10-21 16:57:44,974 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cRefset_LanguageSnapshot_NL_20200930.txt
2021-10-21 16:57:48,581 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_iisssccRefset_ExtendedMapSnapshot_NL_20200930.txt
2021-10-21 16:57:48,834 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_sccRefset_CorrelatedExtendedMapTypeReferenceSetSnapshot_NL_2020                                                                              0930.txt
2021-10-21 16:57:48,835 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_scRefset_CorrelatedMapTypeReferenceSetSnapshot_NL_20200930.txt
2021-10-21 16:57:48,836 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_sRefset_SimpleMapSnapshot_NL_20200930.txt
2021-10-21 16:57:49,360 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cciRefset_RefsetDescriptorSnapshot_NL_20200930.txt
2021-10-21 16:57:49,374 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_ciRefset_DescriptionTypeSnapshot_NL_20200930.txt
2021-10-21 16:57:49,377 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cissccRefset_MRCMAttributeDomainSnapshot_NL_20200930.txt
2021-10-21 16:57:49,388 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_cRefset_MRCMModuleScopeSnapshot_NL_20200930.txt
2021-10-21 16:57:49,389 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_ssccRefset_MRCMAttributeRangeSnapshot_NL_20200930.txt
2021-10-21 16:57:49,401 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_ssRefset_ModuleDependencySnapshot_NL_20200930.txt
2021-10-21 16:57:49,402 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_sssssssRefset_MRCMDomainSnapshot_NL_20200930.txt
2021-10-21 16:57:49,403 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_Concept_Snapshot_NL_20200930.txt
2021-10-21 16:57:49,524 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_Description_Snapshot_NL_20200930.txt
2021-10-21 16:57:51,230 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_Identifier_Snapshot_NL_20200930.txt
2021-10-21 16:57:51,231 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_Relationship_Snapshot_NL_20200930.txt
2021-10-21 16:57:52,985 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_sRefset_OWLExpressionSnapshot_NL_20200930.txt
2021-10-21 16:57:53,586 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_StatedRelationship_Snapshot_NL_20200930.txt
2021-10-21 16:57:54,167 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Unzipping file to C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\sct2_TextDefinition_Snapshot_NL_20200930.txt
2021-10-21 16:57:54,234 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - RF2 release filename not recognised 'sct2_Identifier_Snapshot_NL_20200930.tx                                                                              t'. This file will not be loaded.
2021-10-21 16:57:54,235 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Loading SNAPSHOT release files ReleaseFiles{conceptPaths=[C:\Users\j_ent\App                                                                              Data\Local\Temp\temp-rf2-unzip5198274632394087275\1\sct2_Concept_Snapshot_NL_202                                                                              00930.txt], descriptionPaths=[C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip51                                                                              98274632394087275\1\sct2_Description_Snapshot_NL_20200930.txt], textDefinitionPa                                                                              ths=[C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\sct2_                                                                              TextDefinition_Snapshot_NL_20200930.txt], relationshipPaths=[C:\Users\j_ent\AppD                                                                              ata\Local\Temp\temp-rf2-unzip5198274632394087275\1\sct2_Relationship_Snapshot_NL                                                                              _20200930.txt], concreteRelationshipPaths=[], statedRelationshipPaths=[C:\Users\                                                                              j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\sct2_StatedRelation                                                                              ship_Snapshot_NL_20200930.txt], refsetPaths=[C:\Users\j_ent\AppData\Local\Temp\t                                                                              emp-rf2-unzip5198274632394087275\1\der2_cciRefset_RefsetDescriptorSnapshot_NL_20                                                                              200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\                                                                              1\der2_ciRefset_DescriptionTypeSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\                                                                              Local\Temp\temp-rf2-unzip5198274632394087275\1\der2_cissccRefset_MRCMAttributeDo                                                                              mainSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip51                                                                              98274632394087275\1\der2_cRefset_AssociationSnapshot_NL_20200930.txt, C:\Users\j                                                                              _ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\der2_cRefset_Attribu                                                                              teValueSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzi                                                                              p5198274632394087275\1\der2_cRefset_LanguageSnapshot_NL_20200930.txt, C:\Users\j                                                                              _ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\der2_cRefset_MRCMMod                                                                              uleScopeSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unz                                                                              ip5198274632394087275\1\der2_iisssccRefset_ExtendedMapSnapshot_NL_20200930.txt,                                                                               C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\der2_Refse                                                                              t_SimpleSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unz                                                                              ip5198274632394087275\1\der2_sccRefset_CorrelatedExtendedMapTypeReferenceSetSnap                                                                              shot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632                                                                              394087275\1\der2_scRefset_CorrelatedMapTypeReferenceSetSnapshot_NL_20200930.txt,                                                                               C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\der2_sRef                                                                              set_SimpleMapSnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf                                                                              2-unzip5198274632394087275\1\der2_ssccRefset_MRCMAttributeRangeSnapshot_NL_20200                                                                              930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip5198274632394087275\1\d                                                                              er2_ssRefset_ModuleDependencySnapshot_NL_20200930.txt, C:\Users\j_ent\AppData\Lo                                                                              cal\Temp\temp-rf2-unzip5198274632394087275\1\der2_sssssssRefset_MRCMDomainSnapsh                                                                              ot_NL_20200930.txt, C:\Users\j_ent\AppData\Local\Temp\temp-rf2-unzip519827463239                                                                              4087275\1\sct2_sRefset_OWLExpressionSnapshot_NL_20200930.txt]}
2021-10-21 16:57:54,235 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Gathering effective dates for effective component filtering.
2021-10-21 16:57:54,254 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading concepts
2021-10-21 16:57:54,823 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 489842 concepts read from sct2_Concept_Snapshot_NL_20200930.txt
2021-10-21 16:57:54,826 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - includedReferenceSetPathPatterns: [der2_cRefset_Language.*, .*_sRefset_OWL.*                                                                              , .*_cissccRefset_MRCMAttributeDomain.*]
2021-10-21 16:57:54,826 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'der2_cissccRefset_MRCMAttributeDomainSnapshot_NL_20200930.txt' match                                                                              es pattern '.*_cissccRefset_MRCMAttributeDomain.*'
2021-10-21 16:57:54,828 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'der2_cRefset_LanguageSnapshot_NL_20200930.txt' matches pattern 'der2                                                                              _cRefset_Language.*'
2021-10-21 16:57:54,829 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'sct2_sRefset_OWLExpressionSnapshot_NL_20200930.txt' matches pattern                                                                               '.*_sRefset_OWL.*'
2021-10-21 16:57:54,829 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading relationships
2021-10-21 16:57:59,416 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 3119637 relationships read from sct2_Relationship_Snapshot_NL_20200930.txt
2021-10-21 16:57:59,416 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading concrete relationships
2021-10-21 16:57:59,416 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading relationships
2021-10-21 16:58:00,746 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 1051757 relationships read from sct2_StatedRelationship_Snapshot_NL_20200930                                                                              .txt
2021-10-21 16:58:00,746 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading descriptions
2021-10-21 16:58:04,572 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 2263139 descriptions read from sct2_Description_Snapshot_NL_20200930.txt
2021-10-21 16:58:04,572 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading descriptions
2021-10-21 16:58:04,610 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 10138 descriptions read from sct2_TextDefinition_Snapshot_NL_20200930.txt
2021-10-21 16:58:04,610 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading reference set members
2021-10-21 16:58:04,612 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 146 reference set members read from der2_cissccRefset_MRCMAttributeDomainSna                                                                              pshot_NL_20200930.txt
2021-10-21 16:58:04,613 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading reference set members
2021-10-21 16:58:12,166 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 3703602 reference set members read from der2_cRefset_LanguageSnapshot_NL_202                                                                              00930.txt
2021-10-21 16:58:12,168 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading reference set members
2021-10-21 16:58:13,788 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 370929 reference set members read from sct2_sRefset_OWLExpressionSnapshot_NL                                                                              _20200930.txt
2021-10-21 16:58:13,798 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - Reading concepts
2021-10-21 16:58:14,588 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - 489842 concepts read from sct2_Concept_Snapshot_NL_20200930.txt
2021-10-21 16:58:14,588 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - includedReferenceSetPathPatterns: [der2_cRefset_Language.*, .*_sRefset_OWL.*                                                                              , .*_cissccRefset_MRCMAttributeDomain.*]
2021-10-21 16:58:14,588 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'der2_cissccRefset_MRCMAttributeDomainSnapshot_NL_20200930.txt' match                                                                              es pattern '.*_cissccRefset_MRCMAttributeDomain.*'
2021-10-21 16:58:14,588 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'der2_cRefset_LanguageSnapshot_NL_20200930.txt' matches pattern 'der2                                                                              _cRefset_Language.*'
2021-10-21 16:58:14,589 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporte                                                                              r - refset 'sct2_sRefset_OWLExpressionSnapshot_NL_20200930.txt' matches pattern                                                                               '.*_sRefset_OWL.*'
2021-10-21 16:58:14,599 [INFO  ] [pool-1-thread-3] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - Reading relationships
2021-10-21 16:58:14,599 [INFO  ] [pool-1-thread-2] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - Reading concrete relationships
2021-10-21 16:58:14,599 [INFO  ] [pool-1-thread-4] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - Reading descriptions
2021-10-21 16:58:14,599 [INFO  ] [pool-1-thread-5] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - Reading descriptions
2021-10-21 16:58:14,599 [INFO  ] [pool-1-thread-1] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - Reading relationships
2021-10-21 16:58:14,762 [INFO  ] [pool-1-thread-5] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - 10138 descriptions read from sct2_TextDefinition_Snapshot_NL_2020                                                                              0930.txt
2021-10-21 16:58:19,911 [INFO  ] [pool-1-thread-3] org.ihtsdo.otf.snomedboot.Rel                                                                              easeImporter - 1051757 relationships read from sct2_StatedRelationship_Snapshot_                                                                              NL_20200930.txt
2021-10-21 17:12:46,380 [INFO  ] [pool-1-thread-4] org.ihtsdo.otf.snomedboot.ReleaseImporter - Reading reference set members
2021-10-21 17:12:46,380 [INFO  ] [pool-1-thread-1] org.ihtsdo.otf.snomedboot.ReleaseImporter - Reading reference set members
2021-10-21 17:12:47,560 [INFO  ] [pool-1-thread-6] org.ihtsdo.otf.snomedboot.ReleaseImporter - Reading reference set members
2021-10-21 17:13:07,384 [WARN  ] [pool-1-thread-4] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomy - Reference set 900000000000508004 r                     eferences description 751600014 which is not active or does not exist.
2021-10-21 17:15:39,282 [INFO  ] [pool-1-thread-1] org.ihtsdo.otf.snomedboot.ReleaseImporter - 146 reference set members read from der2_c                     issccRefset_MRCMAttributeDomainSnapshot_NL_20200930.txt
2021-10-21 17:15:52,889 [INFO  ] [main] org.ihtsdo.otf.snomedboot.ReleaseImporter - Release files read. JVM total memory is approx 1.829                      MB.
2021-10-21 17:15:53,600 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - Loaded release snapshot
2021-10-21 17:15:53,601 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - Time taken deserialising axioms 0.0s
2021-10-21 17:15:53,601 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - Loading complete.
2021-10-21 17:15:53,602 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - SnomedTaxonomy loaded in 1102.11 secon                     ds
2021-10-21 17:15:53,602 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - 365905 concepts loaded
2021-10-21 17:15:53,602 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - 0 active stated relationships loaded
2021-10-21 17:15:53,609 [INFO  ] [main] org.snomed.otf.owltoolkit.taxonomy.SnomedTaxonomyBuilder - 0 active axioms loaded
org.snomed.otf.owltoolkit.conversion.ConversionException: No Stated Relationships or Axioms were found. An Ontology file can not be produced.
        at org.snomed.otf.owltoolkit.conversion.RF2ToOWLService.convertRF2ArchiveToOWL(RF2ToOWLService.java:51)
        at org.snomed.otf.owltoolkit.Application.rf2ToOwl(Application.java:145)
        at org.snomed.otf.owltoolkit.Application.run(Application.java:88)
        at org.snomed.otf.owltoolkit.Application.main(Application.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)`

**Comment by kaicode** [comment]
Hi @J-rijn, thanks for reaching out!

This is probably a memory related problem. Try giving java at least 4g by adding `-Xms4g ` as the first argument of the `java` command.
[See example](https://github.com/IHTSDO/snomed-owl-toolkit#snomed-rf2-to-owl-file-conversion).

I hope that helps!

**Comment by kaicode** [comment]
@J-rijn I'm sorry, I overlooked your new issue.
You can safely ignore that warning because I don't think any dialect code is required for Dutch. I have added Dutch to the config in the develop branch so that warning should be suppressed in the next release.

**Comment by pseudomonas** [comment]
On dialect codes, I'm dealing with `nl-be` vs `nl-nl`, and while I'm not going to be so precious that I can't accept `nl` as a synonym for `nl-nl`, it sometimes makes coding a bit easier to have it there explicitly.

**Comment by kaicode** [comment]
Yes, the `nl-be` dialect is used in the Belgian SNOMED CT extension for the Belgian Dutch language reference sets. It's not used in the Netherlands SNOMED CT extension.
